[project]
name = "repl-nix-nba-stats-dashboard"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.9.2",
    "nba-api==1.4.1",
    "pandas>=2.2.3",
    "plotly>=5.24.1",
    "streamlit>=1.40.2",
]
